export const DATE = {
  DATE_FORMAT: 'DD-MM-YYYY',
  DATE_FORMAT_V2: 'DD/MM/YYYY',

  DATE_TIME_FORMAT: 'DD/MM/YYYY - HH:mm',
  DATE_TIME_FORMAT_V2: 'YYYY-MM-DD HH:mm',

  TIME_DATE_FORMAT: 'HH:mm DD/MM/YYYY',
  TIME_DATE_FORMAT_V2: 'HH:mm YYYY-MM-DD',

  TIME_FORMAT: 'HH:mm'
} as const
